# Default Title of Site
title: Jumbo Jekyll
# Description of the site used for default meta description
url: http://jumbojekyll.co.uk
baseurl: ""
description: |-
  The Jumbo Jekyll Theme is used across all Linaro static sites.
# Destination of the Jekyll site upon build of site.  
destination: _site
# Default permalink for blog posts
permalink: /blog/:title/ 
# Jumbo Jekyll Theme
theme: jumbo-jekyll-theme
# Syntax highlighter
highlighter: rouge
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Markdown flavour used by Jekyll to parse markdown.
markdown: kramdown
# Email
email: contact@linaro.org
# Company Address
address: > 
  Harston Mill
  Royston Rd, Harston
  Cambridge, United Kingdom
  CB22 7GG
# Default character encoding
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Files Jekyll will ignore when building the static site.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - _site
# Sass Configuration for the site styles
sass:
    style: compressed
    load_paths:
        - assets/css
# Compress HTML using the jekyll-tidy plugin.
jekyll_tidy: 
    # Toggle compression of HTML
    compress_html: true
    # JS Path added to exclude to stop errors.
    exclude: ["assets/**/*.js"] 
# Permalink style to be used for paginating pages in pagination.html
paginate_path: /blog/:num/
paginate_path_news: /news/:num/
paginate_path_authors: /authors/:num/
# Jekyll Pagination V2 Configuration
pagination:
    # Default pagination path for Jekyll Posts
    # For other permalinks set in the front matter of the post index page
    permalink: /:num/
    # Enabled or not?
    enabled: true
    # Home many posts to display by default
    per_page: 5
    # Number of pages to show either side of the current page i.e - 1, 2, {3}, 4, 5
    trail:
        before: 2
        after: 2
    # Reverse the order of paginated pages
    sort_reverse: true
    # Field to sort posts by when paginating
    sort_field: 'date'
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
# Jekyll_get plugin configuration. This will not be needed in all jekyll sites
# only those that are displaying news from the news db or listing Linaro members.
# jekyll_get:
#   data: members
#   json: 'https://github.com/Linaro/db'
# Jekyll defaults - used to set default front matter values to collections and posts
defaults:
  #  Set a default Social Media Image
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
  - scope:
      type: posts 
      path: "_posts"
    values:
      layout: post
      comments: true
  - scope:
        path: ""
        type: "authors"
    values:
        layout: author
# Jekyll Assets setup
assets:
  # Compress JS Assets - uses the uglifier 
  compression: true
  gzip: true
  # Autoprefixer default settings
  autoprefixer:
      browsers: ["last 2 versions","> 5%","IE 9"]
  # These are the paths to look for assets
  sources:
    - assets/js/
    - assets/images/
    - assets/css/    
# Jekyll relative links plugin settings    
jekyll_relative_links:
    process_all_collections: true
    verbose: 1
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - bootstrap-sass
    - uglifier
    - jekyll-assets
    - jekyll-theme-assets-updated
    - jekyll-tidy
    - jekyll-redirect-from
    - jekyll-responsive-image
    - autoprefixer-rails
    - jekyll-paginate-v2
collections:
  authors:
    output: true
    permalink: /author/:name/
# Make sure that Liquid errors stop the build
liquid:
    error_mode: strict    
readme_index:
    enabled:          true
    remove_originals: false

# Jeykyll Responsive Image Configuration
responsive_image:
  cache: false
  # [Required]
  # Path to the image template.
  template: _includes/images/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 400  # [Required] How wide the resized image will be.
      quality: 70 # [Optional] Overrides default_quality for this size.
    - width: 800
      quality: 70

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/foo/bar.png
    - assets/bgs/*.png
    - assets/avatars/*.{jpeg,jpg}