# Default Title of Site
title: Jumbo Jekyll
# Description of the site used for default meta description
url: http://jumbojekyll.co.uk
baseurl: ""
description: |-
  The Jumbo Jekyll Theme is used across all Linaro static sites.
# Destination of the Jekyll site upon build of site.  
destination: _site
# Default permalink for blog posts
permalink: /blog/:title/ 
# Jumbo Jekyll Theme
theme: jumbo-jekyll-theme
# Syntax highlighter
highlighter: rouge
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Markdown flavour used by Jekyll to parse markdown.
markdown: kramdown
# Email
email: contact@linaro.org
# Company Address
address:
  - Harston Mill
  - Royston Rd, Harston
  - Cambridge, United Kingdom
  - CB22 7GG
# Default character encoding
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Files Jekyll will ignore when building the static site.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - _site
  - package.json
  - node_modules
  - gulpfile.js
# Compress HTML using the jekyll-tidy plugin.
jekyll_tidy: 
    # Toggle compression of HTML
    compress_html: true
    # JS Path added to exclude to stop errors.
    exclude: ["assets/**/*.js"] 
# Jekyll Pagination V2 Configuration
pagination:
    permalink: '/:num/'
    enabled: true
    per_page: 9
    trail:
        before: 2
        after: 2
    sort_reverse: true
    sort_field: 'date'
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
# Jekyll_get plugin configuration. This will not be needed in all jekyll sites
# only those that are displaying news from the news db or listing Linaro members.
# jekyll_get:
#   data: members
#   json: 'https://github.com/Linaro/db'
# Jekyll defaults - used to set default front matter values to collections and posts
defaults:
  #  Set a default Social Media Image
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
  - scope:
      type: posts 
      path: "_posts"
    values:
      layout: post
      is_post: true
      comments: true
  - scope:
        path: ""
        type: "authors"
    values:
        layout: author
# Jekyll relative links plugin settings    
jekyll_relative_links:
    process_all_collections: true
    verbose: 1
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-paginate-v2
    - jekyll-picture-tag-latest
collections:
  authors:
    output: true
    permalink: /author/:name/
# Make sure that Liquid errors stop the build
liquid:
    error_mode: strict    
readme_index:
    enabled:          true
    remove_originals: false
picture:
  source: "assets/images"
  output: "assets/images/processed"