# Custom Favicon
favicon: favicon.png
# Placeholder for Missing Images
placeholder: /assets/images/placeholder.png
# Footer Newsletter toggle.
newsletter:
    enabled: false
tags_enabled: true
# Settings for the home page
jumbotron:
    # Darken is set to true by default - if you wish to remove the image overlay
    # then change this setting to false.
    darken: true
error-pages:
  # image: /assets/images/content/path-to-image.jpg
  svg: linaro-404.html
  not-found-title: 404 page not found!
  not-found-desc: Sorry, but the page you were looking for could not be found.
# Blog setup
blog:
    # Show Thumbnails in the post index
    show_thumbnails: true
    # Toggle site wide comments display.
    comments: true
    # Post Side Bar Settings
    sidebar:
        # custom-include: blog-sidebar-include.html
        display-on-posts: true
        display-on-index: true
        # Toggle whether or not thumbnails in the sidebar are displayed.
        thumbnails:
            display: true
        # Display other posts contained in _posts
        other-posts:
            display: true
            count: 4
        # Display Related posts based on tags / categories
        related-posts:
            display: true
            count: 5
        # Display the most recent posts
        most-recent-posts:
            display: true
            count: 5  
# Google Anayltics Setup
# google:
#     tag_manager: GTM-5DLPJQ
# Shema.org settings used in the schema.html include.
# schema:
#     enabled: true
#     organisation:
#         name: Linaro
#         url: https://www.linaro.org
#         sameAs:
#             - https://twitter.com/linaroorg
#             - https://www.facebook.com/LinaroOrg
#             - https://www.linkedin.com/company/1026961/
#             - https://plus.google.com/+LinaroOnAir
#             - https://github.com/Linaro
#             - https://www.slideshare.net/linaroorg
#         address:
#             street: Harston Mill, Royston Rd 
#             town: Harston 
#             county: Cambridge 
#             post_code: CB22 7GG
#             country_code: UK
# Disqus Comments
disqus:
    enabled: false
    shortname: http-www-jumbojekyll-co-uk
# # Mailchimp settings
# mailchimp:
#     enabled: true
#     id: af6cf590b0
# # Breadcrumb Settings
# breadcrumb:
#     image: breadcrumb-image.jpg

# edit-on-github:
#     enabled: true
#     repo: https://www.github.com/Linaro/website
#     docs: https://www.github.com/Linaro/website 
# Jekyll social media site settings. Github, LinkedIn, Google+, Facebook and Youtube
# github_username: Linaro
# linkedin_username: 1026961
# google_plus_username: +LinaroOnAir
# facebook_username: LinaroOrg
# youtube_username: linaroorg
# twitter_username: linaroorg
# slideshare_username: linaroorg